#repository = binaryfiles
#students = students.bin
#assignments = assignments.bin
#grades = grades.bin


#repository = inmemory
#students = ""
#assignments = ""
#grades = ""


repository = textfiles
students = "students.txt"
assignments = "assignments.txt"
grades = "grades.txt"